name: 'slack-deploy-message'
description: 'Send a deploy message to Slack'
author: 'Conventional Actions'
inputs:
  version:
    required: true
    description: 'version'
  bot-token:
    required: false
    description: 'bot token'
    default: ''
  webhook-url:
    required: false
    description: 'webhook URL'
    default: ''
  message:
    required: false
    description: 'Slack message'
    default: ''
  channel-id:
    required: false
    description: 'Slack channel ID'
    default: ''
  webhook-type:
    required: false
    description: 'Webhook type'
    default: 'WORKFLOW_TRIGGER'
  github-token:
    required: false
    description: 'GitHub token'
    default: ${env.GITHUB_TOKEN}
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: hash
  color: purple
